project_id = "pylbfjbfhaulpzrzsosc"

[functions.twitch-auth]
verify_jwt = false

[functions.twitch-client-id]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.update-stream-info]
verify_jwt = false