// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pylbfjbfhaulpzrzsosc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5bGJmamJmaGF1bHB6cnpzb3NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDg4MjUsImV4cCI6MjA3MTc4NDgyNX0.Tf0mgs-KR4AQEr4p2ntczFqNgPqH3xX4bZGHbK1YX1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});